version: '3.9'

volumes:
  postgres_data:

x-api: &api
  build: .
  environment:
    C_FORCE_ROOT: "1"
    PGHOST: db
    PGUSER: postgres
    PGPASSWORD: postgres
    REDIS_URL: redis://redis:6379/0
  volumes:
    - .:/home/skylines/code/
  depends_on:
    - db
    - redis


services:
  db:
    image: postgis/postgis:10-2.5
    volumes:
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 5s

  api:
    <<: *api
    ports:
      - 5000:5000

  worker:
    <<: *api
    command: pipenv run ./manage.py celery runworker

  tracking:
    <<: *api
    command: pipenv run ./manage.py tracking runserver
    ports:
      - 5597:5597/udp
